baseURL = "https://BardiaCrunch/hugotheclock/"
relativeURLs = true
languageCode = "en-us"
theme = "glim-midnight"

[params]
    title = "Bardia-Crunch"
    phrases = [" GAMEDEV ", " GODOT ", " ART ", " UNITY "]
    links = [
    {name = "Github", url = "https://github.com/BardiaCrunch"},    
    {name = "Itch.io", url = "https://bardia-crunch.itch.io"},

    {name = "Bluesky", url = "https://bsky.app/profile/bardia-crunch.bsky.social"}
    ] 
    background = "blank.mp4"
